# Generated by Django 2.2.7 on 2019-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('air_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date aired')),
                ('question', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('answer', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('round', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('show_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
