# Generated by Django 2.2.7 on 2019-12-02 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('air_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date aired')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('round', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('show_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('answer', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Category')),
            ],
        ),
    ]
