# Generated by Django 3.0 on 2019-12-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
